#!/usr/bin/env python3
"""Generate Muse's static 16 px caption font with lv_font_conv 1.5.3.

No network access or firmware secrets are needed. See components/muse/fonts/README.md.
"""
import argparse
import hashlib
import json
import subprocess
import tempfile
from pathlib import Path

FONT_SHA256 = "2c76254f6fc379fddfce0a7e84fb5385bb135d3e399294f6eeb6680d0365b74b"
SYMBOLS = "　、。〈〉《》「」『』【】〔〕〖〗〘〙〚〛〜〝〞〟〰·×÷°—–…‘’“”￥"


def codepoints():
    chars = set(range(0x20, 0x7F)) | set(range(0xFF01, 0xFF5F))
    chars.update(map(ord, SYMBOLS))
    for hi in range(0xB0, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                text = bytes((hi, lo)).decode("gb2312")
            except UnicodeDecodeError:
                continue
            chars.add(ord(text))
    return sorted(chars)


def ranges(chars):
    result = []
    start = end = chars[0]
    for cp in chars[1:] + [None]:
        if cp == end + 1:
            end = cp
            continue
        result.append(f"0x{start:x}" if start == end else f"0x{start:x}-0x{end:x}")
        start = end = cp
    return ",".join(result)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--font", type=Path, required=True)
    ap.add_argument("--converter", type=Path, required=True)
    ap.add_argument("--node", default="node")
    args = ap.parse_args()
    package = json.loads((args.converter.resolve().parent / "package.json").read_text(encoding="utf-8"))
    if package.get("version") != "1.5.3":
        raise SystemExit("lv_font_conv 1.5.3 is required")
    if hashlib.sha256(args.font.read_bytes()).hexdigest() != FONT_SHA256:
        raise SystemExit("Unexpected Noto Sans CJK SC source font; see README for the pinned SHA256")
    out = Path(__file__).resolve().parents[2] / "components/muse/fonts"
    out.mkdir(parents=True, exist_ok=True)
    cps = codepoints()
    cmd = ["--font", str(args.font.resolve()),
           "--size", "16", "--bpp", "2", "--format", "lvgl", "--range", ranges(cps),
           "--no-compress", "--no-kerning", "--lv-font-name", "muse_font_cjk_16",
           "--output", "muse_font_cjk_16.c"]
    # GB2312's sparse Unicode ranges exceed Windows' command-line limit.
    with tempfile.TemporaryDirectory() as tmp:
        options = Path(tmp) / "args.json"
        options.write_text(json.dumps(cmd), encoding="utf-8")
        runner = ("require(process.argv[1]).run(JSON.parse(require('fs').readFileSync(process.argv[2], 'utf8')))"
                  ".catch(e => { console.error(e); process.exit(1); });")
        subprocess.run([args.node, "-e", runner, str(args.converter.resolve().parent / "lib/cli.js"),
                        str(options)], cwd=out, check=True)
    generated = out / "muse_font_cjk_16.c"
    # The converter command embeds machine-specific paths. Keep a reproducible header.
    body = generated.read_text(encoding="utf-8")
    body = body[body.index("#ifndef MUSE_FONT_CJK_16"):]
    header = """/*
 * Muse caption bitmap subset, derived from Noto Sans CJK SC Regular 2.004.
 * Copyright 2014-2021 Adobe (http://www.adobe.com/).
 * Licensed under the SIL Open Font License 1.1; see OFL.txt in this directory.
 * Generated by tools/muse/gen_cjk_font.py using lv_font_conv 1.5.3.
 * 16 px, 2 bpp, uncompressed, no kerning. Do not edit glyph data by hand.
 */

"""
    generated.write_text(header + '#include "lvgl.h"\n\n' + body, encoding="utf-8", newline="\n")
    (out / "codepoints.txt").write_text("".join(chr(cp) for cp in cps) + "\n", encoding="utf-8", newline="\n")
    print(f"Generated {len(cps)} glyphs, including 6763 GB2312 Han characters")


if __name__ == "__main__":
    main()
